### ISSUE TITLE
get Cell State Each time or hidden vector

### ISSUE THREAD

**Issue by ghost** [kamalkraj/Named-Entity-Recognition-with-Bidirectional-LSTM-CNNs#10]
I want to get cell state in time t ,that's C(t), and the hidden vector h(t) or h(t-1),  and weight W and U, so how can I do to get it ?

**Comment by kamalkraj** [comment]
@LittleBella 
https://github.com/keras-team/keras/issues/9351

**Comment by ghost** [comment]
Actually, I don't understand the "Lambda" meaning mentioned at [keras#9351](https://github.com/keras-team/keras/issues/9351), can u give me some help about it ?

**Comment by ghost** [comment]
Lambda is a  Layer in Keras, I'll get it, thanks.
