### ISSUE TITLE
data preparation

### ISSUE THREAD

**Issue by MSOANCAH** [kamalkraj/Named-Entity-Recognition-with-Bidirectional-LSTM-CNNs#13]
Is data preparation/ labelling done manually or any other technique has been used?
If documents are big then this manual labelling is very much time consuming.
So just wanted to know how @kamalkraj  have done it?

**Comment by kamalkraj** [comment]
@MSOANCAH 
The data used in this repo is from `conll 2003 shared task`
I didn't do any tagging/ labelling

If you want to train a model on your own dataset , dataformat should be same as conll 2003 and data preprocessing code for conll 2003 available in this repo.

**Comment by MSOANCAH** [comment]
so if i want to label my data, i have to do it manually??

**Comment by kamalkraj** [comment]
Yes , you have to manually prepare the data

**Comment by MSOANCAH** [comment]
Ok, Thanks, for your quick response
